version: "2"
services:
    web:
        tty: true
        stdin_open: true
        build: .
        command: "/bin/bash"
        volumes:
            - ./:/app
        ports:
            - "3000:3000"
        environment:
            - SESSION_SECRET=heYGakW6qr44eMP
            - ENABLE_GRAPHIQL=true
